import "./App.css";
import "./GenericModalForm.css";
import "./BookOfertas.css";
import "./CompraAgendada.css";
import "./CompraLimitada.css";
import "./CompraMercado.css";
import "./FormInterno.css";
import "./Grafico.css";
import "./BodyHeader.css";
